create database Store;
use Store;
-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

select * from supplier;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);
select * from categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);
select * from employees;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

select * from customers;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from products;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from orders;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from order_details;

-- Question 
-- 1. Customer Insights

-- Que 1. How many unique customer have placed orders ?
select * from customers;

SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;


-- Que 2.  Which customers have placed the highest number of orders?
SELECT c.cust_id, c.cust_name, COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC limit 10;



-- Que 3. What is the total and average purchase value per customer?
select * from customers;

select c.cust_id, c.cust_name,
sum(od.total_price) as total_purchase,
avg(od.total_price) as avg_purchase
from customers c
join orders o on c.cust_id = o.cust_id
join order_details od on o.ord_id= od.ord_id
group by c.cust_id, c.cust_name;

-- Que 4. who are the top 5 customers by total purchase amount?
select c.cust_name, sum(od.total_price) as total_spent
from customers c
join orders o on c.cust_id = o.cust_id
join order_details od on o.ord_id = od.ord_id
group by c.cust_name
order by total_spent Desc
limit 5;

-- 2. Product Performance 
-- Q 1. How many products exist in each category ?
select cat.cat_name, COUNT(p.Prod_id) as total_products
From Categories cat 
Join products p on cat.cat_id = p.cat_id
group by cat.cat_name;

-- Q 2. What is the average price of products by category?
select cat.cat_name, avg(p.price) as avg_price
from categories cat 
join products p on cat.cat_id = p.cat_id
group by cat.cat_name;

-- Q 3. which Products have the highest total sales volume ( by quantity)?
select p.prod_name, sum(od.quantity) as total_quantity_sold
from products p 
join order_details od on p.prod_id = od.prod_id
group by p.prod_name
order by total_quantity_sold DESC;

-- Q 4. What is the total revenue generated by each product ?
select p.prod_name, sum(od.total_price) as total_revenue
from products p 
join order_details od on p.prod_id= od.prod_id
group by p.prod_name;

-- Q 5. How do product sales vary by category and supplier ?
select cat.cat_name, s.sup_name,
sum(od.total_price) as total_sales
from order_details od
join products p on od.prod_id = p.prod_id
join categories cat on p.cat_id= cat.cat_id
join supplier s on p.sup_id = s.sup_id
group by cat.cat_name, s.sup_name;

-- 3. Sales and order Trends
-- Q 1. How many orders have been placed in total ?
select count(*) as total_orders
from orders;

-- Q 2. What is the average value per order? 
select avg(order_total) as avg_order_value
from (
select ord_id, sum(total_price) as order_total
from order_details
group  by ord_id
)t;

-- Q 3. On which dates were the most orders placed?
select order_date, count(*) as total_orders
from orders
group by order_date
order by total_orders Desc;

-- Q 4. What are the monthly trends in order volume and revenue ?
select substring(order_date, 1,7) as month,
count(distinct o.ord_id) as total_orders,
sum(od.total_price) as total_revenue
from orders o 
join order_details od on o.ord_id = od.ord_id
group by month;

-- Q 5. How do order patterns vary across weekdays and weekends?

SELECT 
    CASE 
        WHEN DAYOFWEEK(order_date) IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY day_type;



-- 4. Supplier contribution
-- Q 1. How many suppliers are there in the database?
select count(*) as total_suppliers
from supplier;

-- Q 2. Which supplier provides the most products?
select s.sup_name, count(p.prod_id) as total_products
from supplier s 
join products p on s.sup_id = p.sup_id
group by s.sup_name
order by total_products DESC;

-- Q 3. What is the average price of products from each supplier?
select s.sup_name, avg(p.price) as avg_price
from supplier s 
join products p on s.sup_id = p.sup_id
group by s.sup_name;

-- Q 4. What suppliers contribute the most to the total product sales (by revenue) ?
select s.sup_name, sum(od.total_price) as total_revenue
from supplier s 
join products p on s.sup_id= p.sup_id
join order_details od on p.prod_id = od.prod_id
group by sup_name 
order by total_revenue Desc;

-- Q 5. Employee Performance 
-- Q 1. How many employees have processes orders? 
select count( distinct emp_id) as active_employees
from orders;

-- Q 2. Which Employees have handled the most orders?
select e.emp_name, count(o.ord_id) as total_orders
from employees e 
join orders o on e.emp_id = o.emp_id
group by e.emp_name
order by total_orders Desc;

-- Q 3. What is the total sales value processed by each employee?
select e.emp_name, sum(od.total_price) as total_sales
from employees e 
join orders o on e.emp_id = o.emp_id
join order_details od on o.ord_id = od.ord_id
group by e.emp_name;

-- Q 4. What is the average order value handled per employee?

SELECT 
    emp_id,
    AVG(order_total) AS avg_order_value
FROM (
    SELECT 
        o.ord_id,
        o.emp_id,
        SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od
        ON o.ord_id = od.ord_id
    GROUP BY o.ord_id, o.emp_id
) t
GROUP BY emp_id;


-- 6. Order Details Deep Dive 
-- Q 1. What is the relationship between quantity ordered and total price?
select quantity, total_price
from order_details;

-- Q 2. What is the average quantity ordered per product?
select p.prod_name, avg(od.quantity) as avg_quantity
from products p 
join order_details od on p.prod_id = od.prod_id
group by p.prod_name;

-- Q 3. How does the unit price vary across products and orders?
select p.prod_name, od.each_price
from products p 
join order_details od on p.prod_id = od.prod_id;


